### ISSUE TITLE
How to use this with less generated stylesheets?

### ISSUE THREAD

**Issue by tschallacka** [NightlyCommit/css-source-map-rebase#17]
I have this code for generating a less stylesheet and combine it with a sass stylesheet.

How would the rebaser logic fit in this?

gulp.task('less', function () {
  
  var lessStream = gulp.src('./style.less')
    .pipe(less({
    	 relativeUrls: true,
    	 sourceMap: true,
    }).on('error', function (err) {
      console.log(err.message);
    }))
  var scssStream = gulp.src('./style.sass')
  	.pipe(sass())
  
  return merge(lessStream, scssStream)
  	.pipe(cssmin().on('error', function(err) {
      console.log(err);
    }))
    .pipe(rename('closure.css'))    
    .pipe(gulp.dest('../css/'));

});

**Comment by ericmorand** [comment]
Hi @tschallacka 

What is `merge` in your example?

**Comment by tschallacka** [comment]
var merge = require('merge-stream');

**Comment by ericmorand** [comment]
Thanks. Don't know what it does, will just answer your question.

There is currently no gulp plugin for my rebaser. It won't work out of the box due to the fact that gulp expect its plugins to pipe Vinyl instances to the next stream.

But it's actually easy to implement in your own gulpfile.js:

```
const gulp = require('gulp');
const Vinyl = require('vinyl');
const merge = require('merge-stream');
const sass = require('gulp-sass');
const less = require('gulp-less');
const cssmin = require('gulp-cssmin');
const rename = require('gulp-rename');
const {Rebaser} = require('css-source-map-rebase');
const {Transform} = require('stream');

let rebaser = new Rebaser();

let transform = new Transform({
    readableObjectMode: true,
    writableObjectMode: true,
    /**
     * @param {{cwd: string, base: string, path: string, contents: Buffer}} chunk
     * @param encoding
     * @param callback
     */
    transform(chunk, encoding, callback) {
        let data = Buffer.from('');

        rebaser.on('data', (buffer) => {
            data = Buffer.concat([data, buffer]);
        });

        rebaser.write(chunk.contents, encoding, () => {
            let file = new Vinyl({
                cwd: chunk.cwd,
                base: chunk.base,
                path: chunk.path,
                contents: data
            });

            this.push(file);

            callback();
        });
    }
});

gulp.task('less', function () {
    let lessStream = gulp.src('./style.less')
        .pipe(less({
            relativeUrls: true,
            sourceMap: {sourceMapFileInline: true},
        }).on('error', function (err) {
            console.log(err);
        }))
        .pipe(transform)
    ;
    let scssStream = gulp.src('./style.scss')
        .pipe(sass({
            sourceMap: true,
            sourceMapEmbed: true
        }))
        .pipe(transform);

    return merge(lessStream, scssStream)
        .pipe(cssmin().on('error', function (err) {
            console.log(err);
        }))
        .pipe(rename('closure.css'))
        .pipe(gulp.dest('.'));
});
```

Note how I pipe the results from both less and sass streams to the transform that makes use of the rebaser.

Also, you have to provide a source map to the rebaser, so I added the expected options to the SCSS stream initialization.

**Comment by tschallacka** [comment]
Nice! thanks for the pointer and example. I can work with this :-)
